---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: business-profile-service
  tags:
    - rx-business-profile-service
    - travel
spec:
  owner: "Integrationws"
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: RX-Digital-Frontend
  description: "Skeleton of Profile Services"
  annotations:
    backstage.io/kubernetes-id: rx-profile-services
    backstage.io/source-location: url:https://github.com/IntegrationWS/rhdevhub.git
    backstage.io/techdocs-ref: url:https://github.com/IntegrationWS/rhdevhub.git
  tags:
    - rx-digital-frontend
    - travel
  links:
    - url: 'https://commercial-webapp-dev-commercial-webapp.apps.clstr02.dev.rx.int/'
      title: RX Digital
      icon: web
spec:
  type: service
  lifecycle: nonproduction
  owner: "Integrationws"
  system: business-profile-service
  dependsOn:
    - component:default/rx-digital-bff

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rx-digital-bff
  description: “Creation of the Profile”
  links:
    - url: https://callsign-proxyserver-security.apps.clstr02.dev.rx.int/
      title: DigitalWS
      icon: web
    - url: https://app-mte-ra-pilot-a.s10-mtecpeuw1.poc.callsign.com/
      title: INFRAWS
      icon: web
spec:
  type: website
  lifecycle: nonproduction
  owner: “Integrationws"
  system: business-profile-service
  dependsOn:
    - component:default/rx-profile-services

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rx-cs-etg
  description: “Call sign etg”
  links:
    - url: https://b2b-mte-ra-pilot-a.s10-mtecpeuw1.poc.callsign.com
      title: INFRAWS
      icon: web
spec:
  type: website
  lifecycle: nonproduction
  owner: “InfraWS"
  system: business-profile-service
  subcomponentOf: component:default/rx-digital-bff

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rx-cs-auth
  description: “Call sign auth”
  links:
    - url: https://app-mte-ra-pilot-a.s10-mtecpeuw1.poc.callsign.com 
      title: INFRAWS
      icon: web
spec:
  type: website
  lifecycle: nonproduction
  owner: “InfraWS"
  system: business-profile-service
  subcomponentOf: component:default/rx-digital-bff

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rx-api-connect-profile-services
  description: "Skeleton of Profile Services"
  annotations:
    #argocd/app-selector: rht-gitops.com/janus-argocd=rx-digital-build-bootstrap
    backstage.io/kubernetes-id: rx-profile-services
    #janus-idp.io/tekton: rx-rx-profile-services
    backstage.io/source-location: url:https://github.com/IntegrationWS/rhdevhub.git
    backstage.io/techdocs-ref: url:https://github.com/IntegrationWS/rhdevhub.git
    #gitlab.com/project-slug: development/rx-digital-build
    #quay.io/repository-slug: "quayadmin/rx-digital-build"
  tags:
    - create-profile
    - retreive-profile
    - guest-360
    - crm-api
    - cdp-api
  links:
    - url: 'http://10.3.42.77/createprofile/'
      title: Guest 360 Create profile
      icon: web
    - url: 'http://10.3.42.77/searchprofile/'
      title: Guest 360 Create profile)
      icon: web
    - url: https://cpd-cp4i.apps.clstr02.dev.rx.int/integration/kafka-clusters/cp4i/es/
      title: Event Streams
      icon: web
    - url: https://cpd-cp4i.apps.clstr02.dev.rx.int/integration/design/integrations/cp4i/app-des/home
      title: APP Connect Design
      icon: web
    - url: https://datapower-cp4i.apps.clstr02.dev.rx.int/dp/login.xml
      title: Data Power
      icon: web
spec:
  type: service
  lifecycle: nonproduction
  owner: "Integrationws"
  system: business-profile-service
  dependsOn:
    - resource:default/artists-db
  dependencyOf:
    - component:default/artist-web-lookup
  providesApis:
    - rx-create-profile-api
    - rx-update-profile-api
    - rx-retreive-profile-api
  consumesApis:
    - rx-appconnect-orchestrator
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rx-appconnect-orchestrator
  description: "Appconnect backend orchestrator"
  tags:
    - appconnect
spec:
  type: service
  lifecycle: nonproduction
  owner: "Integrationws"
  system: business-profile-service
  providesApis:
    - rx-appconnect-orchestrator
  consumesApis:
    - rx-create-profile-api
    - rx-update-profile-api
    - rx-retreive-profile-api
    - rx-kafka-create-profile
    - rx-kafka-update-profile
---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rx-create-profile-api
  description: “Creation of the Profile”
spec:
  type: openapi
  lifecycle: nonproduction
  owner: “Integrationws"
  system: rbusiness-profile-service
  definition:
    $text: ./openapi-create.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rx-appconnect-orchestrator
  description: “appconnect orchestrator”
spec:
  type: openapi
  lifecycle: nonproduction
  owner: “Integrationws"
  system: business-profile-service
  definition:
    $text: ./openapi-appconnect-orchestrator.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rx-update-profile-api
  description: “Update of the Profile”
spec:
  type: openapi
  lifecycle: nonproduction
  owner: “Integrationws"
  system: business-profile-service
  definition:
    $text: ./openapi.update.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rx-retreive-profile-api
  description: “Retreive of the Profile”
spec:
  type: openapi
  lifecycle: nonproduction
  owner: “Integrationws"
  system: business-profile-service
  definition:
    $text: ./openapi.retreive.yaml

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rx-integration-event-stream
  description: "kafka update profile"
  tags:
    - update-profile
    - create-profile
  links:
    - url: 'https://cpd-cp4i.apps.clstr02.dev.rx.int/integration/kafka-clusters/cp4i/es/topics/RX.PROFILESERVICES.CREATEPROFILE.PROVIDER/messages'
      title: kafka topic to create profile
      icon: web
    - url: 'https://cpd-cp4i.apps.clstr02.dev.rx.int/integration/kafka-clusters/cp4i/es/topics/RX.PROFILESERVICES.UPDATEPROFILE.PROVIDER/messages'
      title: kafka topic to update profile
      icon: web
spec:
  type: kafka
  lifecycle: nonproduction
  system: business-profile-service
  owner: "Integrationws"
  dependsOn:
    - component:rx-appconnect-orchestrator
    - component:rx-kafka-adaptor
  providesApis:
    - rx-kafka-create-profile
    - rx-kafka-update-profile
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rx-kafka-create-profile
  description: “api for create profile in kafka”
  links:
    - url: 'https://cpd-cp4i.apps.clstr02.dev.rx.int/integration/kafka-clusters/cp4i/es/topics/RX.PROFILESERVICES.CREATEPROFILE.PROVIDER/messages'
      title: kafka create profile link
      icon: web
spec:
  type: openapi
  lifecycle: nonproduction
  owner: “Integrationws"
  system: business-profile-service
  definition:
    $text: ./openapi-create.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rx-kafka-update-profile
  description: “api for update profile in kafka”
  links:
    - url: 'https://cpd-cp4i.apps.clstr02.dev.rx.int/integration/kafka-clusters/cp4i/es/topics/RX.PROFILESERVICES.UPDATEPROFILE.PROVIDER/messages'
      title: kafka update profile link
      icon: web
spec:
  type: openapi
  lifecycle: nonproduction
  owner: “Integrationws"
  system: business-profile-service
  definition:
    $text: ./openapi-create.yaml

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rx-kafka-adaptor
  description: "kafka adaptor "
  tags:
    - kafka-adaptor
  links:
    - url: 'https://cpd-cp4i.apps.clstr02.dev.rx.int/integration/kafka-clusters/cp4i/es/topics/RX.PROFILESERVICES.CREATEPROFILE.PROVIDER/messages'
      title: TBD
      icon: web
    - url: 'https://cpd-cp4i.apps.clstr02.dev.rx.int/integration/kafka-clusters/cp4i/es/topics/RX.PROFILESERVICES.UPDATEPROFILE.PROVIDER/messages'
      title: TBD
      icon: web
spec:
  type: service
  lifecycle: nonproduction
  system: business-profile-service
  owner: "Integrationws"
