openapi: 3.0.1
info:
    title: ‘Profile Retreive API’
    description: ‘Allows you to Retreive profiles on Guest 360’
    version: latest
externalDocs:
    url: ’https://apic-gw-gateway-cp4i.apps.clstr02.dev.rx.int/rx-commercial/commercial/profileservices/retrieve’
servers:
    - url: https://customgw-cp4i.apps.clstr02.dev.rx.int/rx-commercial/commercial/profileservices/retrieve
paths:
    /retrieve:
        post:
            operationId: postRetrieve
            responses:
                '200':
                    description: 'The operation was successful.'
                    schema: {$ref: '#/definitions/responseBody_retrieve'}
                '400':
                    description: 'Bad Request.'
                    schema: {$ref: '#/definitions/rxResFail'}
                '422':
                    description: 'Unprocessable Entity.'
                    schema: {$ref: '#/definitions/rxResFail'}
                '500':
                    description: 'Internal Server Error.'
                    schema: {$ref: '#/definitions/rxResFail'}
            consumes:
                - application/json
            produces:
                - application/json
            description: 'Insert a retrieve'
            parameters:
                -
                    name: body
                    in: body
                    schema: {$ref: '#/definitions/requestBody_retrieve'}
                    description: 'The request body for the operation'
                    required: true
basePath: /profileservices/guestretrieveprofile
definitions:
    requestBody_retrieve:
        type: object
        additionalProperties: false
        required:
            - rxReqHeader
            - rxReqData
        properties:
            rxReqHeader:
                $ref: '#/definitions/reqHeader'
            rxReqData:
                type: object
                additionalProperties: false
                properties:
                    customerID: {type: string}
                required:
                    - customerID
    reqHeader:
        type: object
        additionalProperties: false
        properties:
            partnerId:
                type: string
            appId:
                type: string
            channelId:
                type: string
            airlineId:
                type: string
            messageData:
                type: object
                additionalProperties: false
                properties:
                    timestamp: {type: string, pattern: '^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[01][0-9]):[0-5][0-9])?$'}
                required:
                    - timestamp
            securityContext:
                type: object
                additionalProperties: false
                properties:
                    ipAddress: {type: string}
                    ipType: {type: string}
                    macAddress: {type: string}
                required:
                    - ipAddress
                    - ipType
        required:
            - partnerId
            - appId
            - channelId
            - airlineId
            - securityContext
    responseBody_retrieve:
        type: object
        additionalProperties: false
        required:
            - rxResHeader
            - rxResData
        properties:
            rxResHeader:
                $ref: '#/definitions/resHeader'
            rxResData:
                $ref: '#/definitions/resData'
    resHeader:
        type: object
        additionalProperties: false
        properties:
            partnerId:
                type: string
            appId:
                type: string
            channelId:
                type: string
            airlineId:
                type: string
            messageData:
                type: object
                additionalProperties: false
                properties:
                    timestamp: {type: string, pattern: '^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[01][0-9]):[0-5][0-9])?$'}
                required:
                    - timestamp
            securityContext:
                type: object
                additionalProperties: false
                properties:
                    ipAddress: {type: string}
                    ipType: {type: string}
                    macAddress: {type: string}
                required:
                    - ipAddress
                    - ipType
            transactionId:
                type: string
            responseTimestamp:
                type: string
                pattern: '^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[01][0-9]):[0-5][0-9])?$'
            status:
                type: string
        required:
            - partnerId
            - appId
            - channelId
            - airlineId
            - securityContext
    resData:
        type: object
        additionalProperties: false
        properties:
            customerID:
                type: string
            profileStatus:
                type: string
            preferToShareEmergencyContact:
                type: boolean
            profileImageReference:
                type: string
            customerDetails:
                type: object
                additionalProperties: false
                properties:
                    firstName: {type: string}
                    middleName: {type: string}
                    lastName: {type: string}
                    preferredName: {type: string}
                    title: {type: string}
                    dateOfBirth: {type: string}
                    gender: {type: string}
                    email: {type: string}
                    registeredMobile: {type: string}
                    registeredcountryCode: {type: string}
            guestDocuments:
                type: array
                items:
                    type: object
                    additionalProperties: false
                    properties: {documentNumber: {type: string}, typeOfDocument: {type: string}, nationality: {type: string}, issuingCountry: {type: string}, placeOfIssue: {type: string}, issueDate: {type: string}, expiryDate: {type: string}}
            guestAddresses:
                type: array
                items:
                    type: object
                    additionalProperties: false
                    properties: {addressType: {type: string}, addressLine1: {type: string}, addressLine2: {type: string}, addressLine3: {type: string}, street: {type: string}, state: {type: string}, zipCode: {type: string}, city: {type: string}, country: {type: string}}
            guestContacts:
                type: array
                items:
                    type: object
                    additionalProperties: false
                    properties: {contactType: {type: string}, contactDetail: {type: string}, contactExtension: {type: string}, countryCode: {type: string}}
            communicationPreferences:
                type: array
                items:
                    type: object
                    additionalProperties: false
                    properties: {channel: {type: string}, value: {type: boolean}}
            guestPreferences:
                type: array
                items:
                    type: object
                    additionalProperties: false
                    properties: {preferenceType: {type: string}, preferenceValue: {type: array, items: {type: string}}}
            companions:
                type: array
                items:
                    type: object
                    additionalProperties: false
                    properties: {companionTitle: {type: string}, companionFirstName: {type: string}, companionLastName: {type: string}, companionDOB: {type: string}, companionGender: {type: string}, companionEmail: {type: string}, companionPhone: {type: string}, companionGroup: {type: string}, companionDocuments: {type: array, items: {type: object, additionalProperties: false, properties: {documentNumber: {type: string}, typeOfDocument: {type: string}, nationality: {type: string}, issuingCountry: {type: string}, placeOfIssue: {type: string}, issueDate: {type: string}, expiryDate: {type: string}}}}}
            companionGroups:
                type: array
                items:
                    type: string
            favoriteDestinations:
                type: array
                items:
                    type: string
            homeAirports:
                type: array
                items:
                    type: string
            consents:
                type: array
                items:
                    type: object
                    additionalProperties: false
                    properties: {consentType: {type: string}, channel: {type: array, items: {type: string}}}
            favoriteTrip:
                type: array
                items:
                    type: object
                    additionalProperties: false
                    properties: {favoriteTripName: {type: string}, origin: {type: string}, destination: {type: string}, departureDate: {type: string}, returnDate: {type: string}, numberOfTravellers: {type: string}, companions: {type: array, items: {type: object, additionalProperties: false, properties: {companionTitle: {type: string}, companionFirstName: {type: string}, companionLastName: {type: string}, companionDOB: {type: string}, companionGender: {type: string}, companionEmail: {type: string}, companionPhone: {type: string}, companionGroup: {type: string}}}}}
            emergencyContact:
                type: object
                additionalProperties: false
                properties:
                    countryCode: {type: string}
                    email: {type: string}
                    firstName: {type: string}
                    lastName: {type: string}
                    middleName: {type: string}
                    phone: {type: string}
                    relationship: {type: string}
            systemAttributes:
                type: object
                additionalProperties: false
                properties:
                    CreatedBy: {type: string}
                    CreatedOn: {type: string}
                    UpdatedBy: {type: string}
                    UpdatedOn: {type: string}
    rxResFail:
        type: object
        additionalProperties: false
        properties:
            rxResHeader:
                $ref: '#/definitions/resHeader'
            rxResData:
                type: object
                additionalProperties: false
                properties:
                    error: {type: object, additionalProperties: false, properties: {code: {type: string}, desc: {type: array, items: {type: object}}}}

